name: market_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^7.0.0
  google_maps_flutter: ^2.5.3
  firebase_messaging: ^15.0.3
  connectivity: ^3.0.6
  flutter_localizations:
    sdk: flutter

  app_settings: ^5.1.1
  webview_flutter: ^4.8.0
  # fluttertoast: ^4.0.1

  intl_translation:
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^3.2.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^11.2.0

    # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore

  simple_animations: ^5.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_email_sender: ^6.0.3
  # firebase_auth: ^0.16.1
  google_sign_in: ^6.2.1
  # rxdart: ^0.24.1
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  # toast: ^0.1.5
  sqflite: ^2.3.3+1
  # path_provider: ^1.4.0
  another_flushbar: ^1.12.30
  intro_views_flutter: ^3.2.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_zoom_drawer: ^3.2.0
  flutter_carousel_slider: ^1.1.0
  # flare_splash_screen: ^3.0.1

  # getflutter: ^1.0.11
  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/offers/dk_logo.jpg"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/offers/dk_logo.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/offers/


    # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/Fonts/sspu.ttf
        - asset: assets/Fonts/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages